Transformation:
 #pos: {x: 2.95, y: 2.95, z: 0.25}
 #vel: {x: 0.18, y: 0.18, z: 0.01}
  RCB: {xx: 0.0, xy: -1.0, xz: 0.0, yx: -1.0, yy: 0.0, yz: 0.0, zx: 0.0, zy: 0.0, zz: -1.0}
  tCB: {x: 0.05531, y: 0.0, z: 0.01913}
